import { mountPublicPage } from "../shared/bootstrap";
import { activateCompactLayout, PageShell, ProductHeader, SampleAudio } from "../shared/components";

activateCompactLayout();

const defaultScript = `1 あっ、こんにちは〜
2 こんにちは。ご無沙汰してます。
1 元気ですか？最近、どうしてます？
2 いや〜、仕事が忙しくて。AIの進化がすごくて大変なことになってます
1 AIの進化凄いですよね〜。どんどん賢くなってますよね`;

function VoiceSlot({ slot }: { slot: number }) {
  return <label className="vibevoice-upload-slot react-voice-slot"><span className="vibevoice-upload-index">{slot}</span><strong>Speaker {slot}</strong><input type="file" name={`voice_file_${slot}`} accept="audio/*,video/*"/><span className="vibevoice-upload-actions"><span className="vibevoice-upload-action">ファイル</span><button className="vibevoice-record-slot-button" type="button" data-record-voice-slot={slot}>録音</button><button className="vibevoice-tab-audio-slot-button" type="button" data-tab-audio-slot={slot}>タブ音声</button><button className="vibevoice-url-slot-button" type="button" data-reference-url-open-slot={slot} data-local-reference-url hidden>URL</button></span><small className="vibevoice-saved-voice" data-saved-voice-slot={slot}>未保存</small><small className="vibevoice-url-voice" data-reference-url-display-slot={slot} data-local-reference-url hidden/><audio className="vibevoice-saved-voice-preview" data-saved-voice-preview-slot={slot} controls preload="metadata" hidden aria-label={`Speaker ${slot} 参照音声プレビュー`}/></label>;
}

function HiddenSettings() {
  return <div className="vibevoice-simple-hidden-settings" hidden><button id="vibevoice-reset-settings-button" type="button">初期設定に戻す</button><select name="backend" id="vibevoice-backend" defaultValue="runpod_serverless"><option value="local">ローカル</option><option value="runpod_serverless">RunPod Serverless</option></select><select name="model_id" id="vibevoice-model-id" defaultValue="vibevoice-large-aoi-pinned"><option value="vibevoice-1.5b-pinned">VibeVoice 1.5B 固定版</option><option value="vibevoice-1.5b-latest">VibeVoice 1.5B 最新</option><option value="vibevoice-large-aoi-pinned" data-vibevoice-backends="runpod_serverless" data-vibevoice-auto-line-by-line="false">VibeVoice Large (RunPod)</option></select>{[["cfg_scale","1.3"],["inference_steps","10"],["seed","42"],["temperature","0.95"],["top_p","0.95"],["top_k","0"],["max_voice_seconds","5"],["line_gap","1"],["directed_retry_score_threshold","0.65"],["directed_retry_max_multiplier","1"]].map(([name,value]) => <input key={name} name={name} type="hidden" value={value}/>) }<label><input name="do_sample" type="checkbox" defaultChecked/> do_sample</label><label><input id="vibevoice-line-by-line" name="line_by_line" type="checkbox"/> line_by_line</label><label><input id="vibevoice-directed-line-mode" name="directed_line_mode" type="checkbox" defaultChecked/> directed_line_mode</label><label><input id="vibevoice-directed-retry-low-score" name="directed_retry_low_score" type="checkbox" defaultChecked/> directed_retry_low_score</label></div>;
}

function SkitVoice() {
  return <PageShell className="vibevoice-shell vibevoice-simple-shell react-skit-shell">
    <ProductHeader product="SkitVoice" title="声を選んで、会話をつくる" />
    <section className="react-intro-grid react-skit-intro"><div className="react-intro-copy"><p className="react-step-label">MULTI-SPEAKER GENERATION</p><h2>短い台本から、演じ分けた音声へ。</h2><p>台本と話者ごとの参照音声を選ぶだけ。言語判定と翻訳を自動で行い、複数話者の会話を生成します。</p></div></section>
    <section className="react-output-samples" aria-labelledby="skitvoice-output-samples-title"><h2 id="skitvoice-output-samples-title">出力音声サンプル</h2><div className="react-sample-stack"><SampleAudio feature="skitvoice" language="en-US" label="英語" fixedTitle customControls/><SampleAudio feature="skitvoice" language="zh-CN" label="中国語" fixedTitle customControls/><SampleAudio feature="skitvoice" language="ja-JP" label="日本語" fixedTitle customControls/></div></section>
    <form id="vibevoice-form" className="vibevoice-form react-skit-form"><div className="vibevoice-simple-grid react-skit-grid"><div className="vibevoice-simple-col-main"><section className="vibevoice-panel vibevoice-script-panel react-work-card" aria-label="台本"><div className="vibevoice-panel-header"><div><p className="vibevoice-section-label">01 · SCRIPT</p><h2>台本</h2></div><div className="vibevoice-script-actions"><button id="vibevoice-generate-script-button" className="secondary-button" type="button">台本自動生成</button><label className="vibevoice-file-button"><span>テキストファイル</span><input id="vibevoice-script-file" type="file" name="script_file" accept=".txt,text/plain"/></label></div></div><textarea id="vibevoice-script" name="script" rows={8} placeholder="1 こんにちは。&#10;2 元気ですか？" defaultValue={defaultScript}/><p className="vibevoice-help">行頭に 1-4 / A-D を付けると話者を指定できます。</p></section>
      <section className="vibevoice-panel vibevoice-voice-panel react-work-card" aria-label="参照音声"><div className="vibevoice-panel-header"><div><p className="vibevoice-section-label">02 · VOICES</p><h2>参照音声</h2></div><p>ファイル・録音・タブ音声から選択</p></div><div className="vibevoice-voice-grid">{[1,2,3,4].map(slot => <VoiceSlot slot={slot} key={slot}/>)}</div></section></div>
      <div className="vibevoice-simple-col-side"><section className="vibevoice-panel vibevoice-simple-settings-panel react-generate-card" aria-label="生成"><div className="vibevoice-panel-header"><div><p className="vibevoice-section-label">03 · GENERATE</p><h2>生成設定</h2></div></div><HiddenSettings/><label className="vibevoice-setting-field vibevoice-setting-wide">出力言語<select name="output_language" id="vibevoice-output-language" defaultValue="zh-CN"><option value="en-US">🇺🇸 英語</option><option value="zh-CN">🇨🇳 中国語</option><option value="ja-JP">🇯🇵 日本語（低品質）</option></select></label><p className="vibevoice-rights-confirmation">個人・家庭内の私的利用を超えて公開・共有する場合は、音声の利用条件を確認してください。</p><div className="vibevoice-actions"><button id="vibevoice-generate-button" className="vibevoice-generate-button" type="submit">音声を生成</button><button id="vibevoice-cancel-button" className="vibevoice-cancel-button" type="button" hidden>キャンセル</button><p id="vibevoice-message" className="vibevoice-message" role="status" aria-live="polite"/><div id="vibevoice-job-progress" className="vibevoice-job-progress" hidden><div className="vibevoice-progress-bar" role="progressbar" aria-label="生成進捗" aria-valuemin={0} aria-valuemax={100}><span/></div><p id="vibevoice-timing" className="vibevoice-timing"/><pre id="vibevoice-progress-log" className="vibevoice-progress-log" aria-live="polite"/></div></div></section></div></div></form>
    <p className="public-privacy-notice react-privacy-note react-form-privacy-note" data-public-privacy-notice>参照音声と生成内容は外部の音声処理APIへ送信され、公開デモでは設定に応じて短い履歴を保存する場合があります。機密情報は入力しないでください。</p>
    <ReferenceDialog/><ResultPanel/><details className="vibevoice-debug-runtime" hidden><summary><span>実行環境</span><span id="vibevoice-runtime-status" className="vibevoice-runtime-status" role="status" aria-live="polite">確認中...</span></summary><dl id="vibevoice-runtime-details" className="vibevoice-runtime-details"/></details>
  </PageShell>;
}

function ReferenceDialog() { return <dialog id="vibevoice-reference-url-dialog" className="vibevoice-reference-url-dialog" aria-labelledby="vibevoice-reference-url-title" data-local-reference-url hidden><div className="vibevoice-reference-url-dialog-body"><header className="vibevoice-dialog-header"><div><p className="vibevoice-section-label">URL</p><h2 id="vibevoice-reference-url-title">Speaker <span id="vibevoice-reference-url-title-slot">1</span> のURL参照</h2></div><button id="vibevoice-reference-url-cancel" className="vibevoice-dialog-close" type="button" aria-label="閉じる">×</button></header><input id="vibevoice-reference-url-slot" type="hidden" value="1"/><label className="vibevoice-setting-field vibevoice-setting-wide">動画・音声URL<input id="vibevoice-reference-url" type="url" placeholder="https://youtu.be/...?...&t=1m15s"/></label><div className="vibevoice-reference-url-dialog-grid"><label className="vibevoice-setting-field">開始秒<input id="vibevoice-reference-url-start" type="number" min="0" step="0.1" placeholder="URLの時刻"/></label><label className="vibevoice-setting-field">切り出し秒数<input id="vibevoice-reference-url-duration" type="number" min="0.5" max="30" step="0.5" defaultValue="5"/></label></div><div className="vibevoice-reference-url-actions"><button id="vibevoice-reference-url-clear" className="vibevoice-reference-url-clear" type="button">URL参照を解除</button><button id="vibevoice-reference-url-button" className="vibevoice-reference-url-button" type="button">設定</button></div><p id="vibevoice-reference-url-status" className="vibevoice-reference-url-status" role="status" aria-live="polite"/></div></dialog>; }

function ResultPanel() { return <section id="vibevoice-result" className="vibevoice-result react-result-card" aria-label="生成結果" hidden><div className="vibevoice-panel-header"><div><p className="vibevoice-section-label">RESULT</p><h2>生成結果</h2></div><a id="vibevoice-download" className="vibevoice-download" href="#" download="vibevoice-output.wav">音声を保存</a></div><audio id="vibevoice-audio" controls/><section id="vibevoice-translated-script-section" className="vibevoice-translated-script" hidden><h3>翻訳後の台本</h3><pre id="vibevoice-translated-script"/></section><section className="vibevoice-artifacts-section" aria-label="中間音声"><h3>行ごとの音声</h3><div id="vibevoice-artifacts" className="vibevoice-artifacts"/></section><details className="vibevoice-simple-debug" hidden><summary>診断とVV入力</summary><section className="vibevoice-speaker-scripts-section" aria-label="VV入力テキスト"><h3>VV入力テキスト</h3><div id="vibevoice-speaker-scripts" className="vibevoice-speaker-scripts"/></section><div className="vibevoice-result-grid"><section><h3>正規化後の台本</h3><pre id="vibevoice-normalized-script"/></section><section><div className="vibevoice-result-section-header"><h3>診断</h3><button id="vibevoice-copy-diagnostics" className="vibevoice-copy-button" type="button">コピー</button></div><pre id="vibevoice-diagnostics"/></section></div></details></section>; }

mountPublicPage(<SkitVoice />, ["/static/app_public_session.js", "/static/app_sample_audio_controls.js", "/static/app_public_sample_audio.js", "/static/app_vibevoice.js"]);
