import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const practiceSource = await readFile(new URL("../src/mo_speech/web/app_practice.js", import.meta.url), "utf8");
const practicePlaybackSource = await readFile(new URL("../src/mo_speech/web/practice_playback.js", import.meta.url), "utf8");
const practiceAdminHtml = await readFile(new URL("../src/mo_speech/web/practice_admin.html", import.meta.url), "utf8");
const practiceHistorySource = await readFile(new URL("../src/mo_speech/web/app_practice_history.js", import.meta.url), "utf8");
const publicSessionSource = await readFile(new URL("../src/mo_speech/web/app_public_session.js", import.meta.url), "utf8");
const publicAccessSettingsSource = await readFile(new URL("../src/mo_speech/web/app_public_access_settings.js", import.meta.url), "utf8");
const publicSampleAudioSource = await readFile(new URL("../src/mo_speech/web/app_public_sample_audio.js", import.meta.url), "utf8");
const publicSampleAudioAdminSource = await readFile(
  new URL("../src/mo_speech/web/app_public_sample_audio_admin.js", import.meta.url),
  "utf8",
);
const sampleAudioControlsSource = await readFile(new URL("../src/mo_speech/web/app_sample_audio_controls.js", import.meta.url), "utf8");
const adminHtml = await readFile(new URL("../src/mo_speech/web/index.html", import.meta.url), "utf8");
const adminSource = await readFile(new URL("../src/mo_speech/web/app.js", import.meta.url), "utf8");
const adminHistorySource = await readFile(new URL("../src/mo_speech/web/app_history.js", import.meta.url), "utf8");
const styles = await readFile(new URL("../src/mo_speech/web/styles.css", import.meta.url), "utf8");

test("admin page can start RunPod warmup manually", () => {
  assert.match(adminHtml, /id="runpod-warmup-button"/);
  assert.match(adminHtml, /id="runpod-warmup-status"/);
  assert.match(adminHtml, /id="public-access-panel"/);
  assert.match(adminHtml, /data-public-access-features="voice_conversion"/);
  assert.match(adminHtml, /data-public-feature="voice_conversion"/);
  assert.match(adminHtml, /data-public-feature-setting="audio_max_bytes"/);
  assert.match(adminHtml, /data-public-setting="google_login_required"/);
  assert.match(adminHtml, /data-public-samples-admin/);
  assert.match(adminHtml, /data-public-samples-features="voice_conversion"/);
  assert.match(adminHtml, /data-public-sample-admin-feature="voice_conversion"/);
  assert.doesNotMatch(adminHtml, /data-public-sample-admin-feature="fun"/);
  assert.match(adminHtml, /\/static\/app_public_access_settings\.js/);
  assert.match(adminHtml, /\/static\/app_public_sample_audio_admin\.js/);
  assert.ok(adminHtml.indexOf("runpod-warmup-panel") < adminHtml.indexOf("operation_mode"));
  assert.match(adminSource, /runpodWarmupButton\.addEventListener\("click", startRunpodWarmup\)/);
  assert.match(adminSource, /fetch\("\/api\/warmup", \{ method: "POST" \}\)/);
  assert.match(adminSource, /fetch\(`\/api\/warmup\/\$\{encodeURIComponent\(jobId\)\}`\)/);
  assert.match(publicSampleAudioAdminSource, /\/api\/public-sample-audios/);
  assert.match(publicSampleAudioAdminSource, /method:\s*"DELETE"/);
  assert.match(publicSampleAudioAdminSource, /data-public-sample-admin-feature/);
  assert.match(publicSampleAudioAdminSource, /data-public-sample-delete/);
  assert.match(publicSampleAudioAdminSource, /setPublicSampleActionButton/);
});

test("SpeakLoop controller keeps pronunciation training separate from conversion demo", () => {
  assert.match(practiceSource, /\/api\/practice\/recordings/);
  assert.match(practiceSource, /form\.append\("recording_intent", recordingIntent\)/);
  assert.match(practiceSource, /current_target_text/);
  assert.match(practiceSource, /localStorage\.getItem/);
  assert.match(practiceSource, /localStorage\.setItem/);
  assert.match(practiceSource, /chinese_script/);
  assert.match(practiceSource, /toTraditional/);
  assert.doesNotMatch(practiceSource, /zhTraditionalToSimplified/);
  assert.match(practiceSource, /speed:/);
  assert.doesNotMatch(practiceSource, /auto_play_comparison|autoPlayComparisonControl/);
  assert.match(practiceSource, /renderAttemptResult\(completed\.result\);[\s\S]*setBusy\(false, ""\);[\s\S]*playComparisonAudios\(\)\.catch/);
  assert.doesNotMatch(practiceSource, /asr_model:/);
  assert.match(practiceSource, /Math\.round\(parsed \/ 0\.1\) \* 0\.1/);
  assert.match(practiceSource, /Math\.max\(0\.5/);
  assert.doesNotMatch(practiceSource, /openPracticeSettings/);
  assert.doesNotMatch(practiceSource, /closePracticeSettings/);
  assert.match(practiceSource, /syncCurrentLanguageLabel/);
  assert.match(practiceSource, /playAudioWithCurrentSpeed/);
  assert.doesNotMatch(practiceSource, /segment_mode:/);
  assert.doesNotMatch(practiceSource, /segmentModeSelect|nextPromptButton/);
  assert.match(practiceSource, /function practiceAsrModel\(\)\s*\{[^}]*return "whisper-1"/s);
  assert.match(practiceSource, /form\.append\("comparison_model", comparisonModelSelect\.value\)/);
  assert.match(practiceSource, /form\.append\("playback_padding_seconds", normalizedPlaybackPadding/);
  assert.match(practiceSource, /const defaultComparisonModel = "gpt-5\.6-terra"/);
  assert.match(practiceSource, /const defaultPlaybackPaddingSeconds = 0\.3/);
  assert.match(practiceSource, /\/api\/runtime/);
  assert.match(practiceSource, /practice_developer_settings/);
  assert.match(practiceSource, /practice_history_preview/);
  assert.match(practiceSource, /\/api\/practice-history/);
  assert.match(practiceSource, /renderAttemptResult\(diagnostics\)/);
  assert.match(practiceSource, /recomputed-comparison/);
  assert.match(practiceSource, /function applyPracticeComparisonAlignments/);
  assert.match(practiceSource, /form\.append\("progress_mode", "job"\)/);
  assert.match(practiceSource, /\/api\/practice\/prompt-jobs\//);
  assert.match(practiceSource, /case "transcribing_prompt":[\s\S]*録音を文字にしています/);
  assert.match(practiceSource, /case "translating_prompt":[\s\S]*学習言語へ翻訳しています/);
  assert.match(practiceSource, /case "synthesizing_prompt":[\s\S]*お手本音声を作っています/);
  assert.match(practiceSource, /case "evaluating_comparison":[\s\S]*比較結果を作っています/);
  assert.match(practiceSource, /comparison_model:/);
  assert.match(practiceSource, /playback_padding_seconds:/);
  assert.match(practiceSource, /payload\.overall_score/);
  assert.match(practiceSource, /payload\.overall_comment/);
  assert.match(practiceSource, /payload\.llm_comparison\?\.phrases/);
  assert.match(practiceSource, /比較結果を作成できませんでした。もう一度お試しください。/);
  assert.match(practiceSource, /comparison_alignment/);
  assert.match(practiceSource, /include_pinyin/);
  assert.match(practiceSource, /currentTargetPinyinStatus/);
  assert.match(practiceSource, /renderTargetDisplay/);
  assert.match(practiceSource, /createPinyinRubyFragment/);
  assert.match(practiceSource, /document\.createElement\("ruby"\)/);
  assert.match(practiceSource, /document\.createElement\("rt"\)/);
  assert.match(practiceSource, /ピンインを生成できませんでした/);
  assert.match(practiceSource, /selectedTargetLanguage === "zh-CN" \? true : settings\.show_pinyin !== false/);
  assert.match(practiceSource, /pinyinToggle\.checked = true/);
  assert.match(practiceSource, /\[modelAudio, repeatAudio\]\.forEach/);
  assert.match(practiceSource, /audio\.playbackRate/);
  assert.match(practiceSource, /audio\.defaultPlaybackRate/);
  assert.match(practiceSource, /playing/);
  assert.match(practiceSource, /loadedmetadata/);
  assert.match(practiceSource, /isComparisonPlaying/);
  assert.match(practiceSource, /stopComparisonPlayback/);
  assert.match(practiceSource, /function cancelRecording/);
  assert.match(practiceSource, /recordingCancelled/);
  assert.match(practiceSource, /録音をキャンセルしました/);
  assert.match(practiceSource, /function pausePlaybackForRecording[\s\S]*modelAudio\.pause\(\)[\s\S]*repeatAudio\.pause\(\)/);
  assert.match(practiceSource, /比較再生/);
  assert.match(practiceSource, /setActiveRecordSlot/);
  assert.match(practiceSource, /repeatRecordButton/);
  assert.doesNotMatch(practiceSource, /const\s+\w+\s*=\s*currentTargetText\s*\?\s*"repeat"\s*:\s*"native"/);
  assert.match(practiceSource, /recognizedTextMatchesLearningLanguage/);
  assert.doesNotMatch(practiceSource, /hasPairedComparisonAlignment/);
  assert.match(practiceSource, /renderRecognizedDiff/);
  assert.match(practiceSource, /playbackContract\.buildPracticeDiffCells/);
  assert.match(practicePlaybackSource, /function buildPracticeDiffCells/);
  assert.match(practiceSource, /function renderLlmFeedbackText\(payload\) \{\s*renderRecognizedDiff\(payload\)/);
  assert.doesNotMatch(practiceSource, /renderPracticeGrade/);
  assert.match(practiceSource, /practice-diff-correction/);
  assert.doesNotMatch(practiceSource, /抜け:/);
  assert.match(practiceSource, /practice-diff-cell/);
  assert.match(practicePlaybackSource, /heard: "_"/);
  assert.match(practicePlaybackSource, /targetOffset:\s*targetIndex/);
  assert.match(practiceSource, /playComparisonAudios\(\{\s*targetOffset:\s*cell\.targetOffset\s*\}\)/);
  assert.doesNotMatch(practiceSource, /element\.addEventListener\("click", playComparisonAudios\)/);
  assert.match(practiceSource, /repeatAudio\.src/);
  assert.match(practiceSource, /currentAttemptComparisonAlignment/);
  assert.match(practiceSource, /currentModelComparisonAlignment/);
  assert.doesNotMatch(practiceSource, /comparisonAlignmentPlaybackRanges/);
  assert.match(practiceSource, /\/api\/practice\/attempt-jobs/);
  assert.match(practiceSource, /form\.append\("use_own_voice", ownVoiceToggle\.checked \? "true" : "false"\)/);
  assert.match(practiceSource, /\/api\/practice\/voice-jobs\//);
  assert.match(practiceSource, /voice_conversion_job/);
  assert.match(practiceSource, /renderPracticeJobStatus/);
  assert.match(practicePlaybackSource, /全体比較再生/);
  assert.match(practicePlaybackSource, /一部フレーズ比較再生/);
  assert.match(practicePlaybackSource, /フレーズごと比較再生/);
  assert.match(practicePlaybackSource, /no_speech/);
  assert.match(practiceSource, /currentComparisonPlaybackPlan/);
  assert.doesNotMatch(practiceSource, /canUsePhraseComparisonPlayback/);
  assert.match(practiceSource, /playAudioSegmentToEnd/);
  assert.match(styles, /\.practice-shell\s*\{[^}]*min-height:\s*100svh/s);
  assert.match(styles, /\.practice-shell\s*\{[^}]*align-content:\s*start/s);
  assert.match(styles, /\.practice-header h1\s*\{[^}]*font-size:\s*clamp\(26px/s);
  assert.match(styles, /\.practice-header-auth/);
  assert.match(styles, /\.public-status-bar/);
  assert.match(styles, /\.practice-flow\s*\{[^}]*grid-template-columns:\s*1fr/s);
  assert.match(styles, /\.practice-card-primary\s*\{[^}]*grid-template-columns:\s*auto minmax\(0,\s*1fr\)/s);
  assert.match(styles, /\.practice-repeat-record-button/);
  assert.match(styles, /\.practice-record-orb\.is-inactive/);
  assert.match(styles, /\.practice-record-orb\s*\{[^}]*width:\s*clamp\(64px,\s*8vw,\s*84px\)/s);
  assert.match(styles, /\.practice-quick-settings/);
  assert.match(styles, /\.practice-language-select/);
  assert.doesNotMatch(styles, /\.practice-auto-play-control/);
  assert.match(styles, /\.practice-grade-guide/);
  assert.doesNotMatch(styles, /\.practice-settings-overlay/);
  assert.doesNotMatch(styles, /\.practice-settings-dialog/);
  assert.match(styles, /\.public-auth-panel/);
  assert.match(styles, /\.public-access-admin/);
  assert.match(styles, /\.public-access-feature/);
  assert.doesNotMatch(styles, /\.practice-language-grid\s*\{[^}]*grid-template-columns:\s*repeat\(3/s);
  assert.doesNotMatch(styles, /\.practice-asr-row/);
  assert.doesNotMatch(styles, /\.practice-asr-help/);
  assert.match(styles, /\.practice-recognized-text\s*\{[^}]*font-size:\s*clamp\(19px,\s*3\.6vw,\s*32px\)/s);
  assert.match(styles, /\.practice-target-text\.has-ruby/s);
  assert.match(styles, /\.practice-target-text rt/s);
  assert.match(styles, /\.practice-diff-correction/);
  assert.match(styles, /\.practice-diff-cell\.is-substitute/);
  assert.match(styles, /\.practice-diff-cell\.is-delete/);
  assert.match(styles, /\.practice-diff-heard/);
  assert.doesNotMatch(styles, /\.practice-next-prompt-button/);
  assert.doesNotMatch(styles, /\.practice-repeat-card\s*\{[^}]*order:\s*-1/s);
  assert.doesNotMatch(styles, /\.practice-actions/);
  assert.doesNotMatch(styles, /\.practice-target-text-box\s*\{[^}]*overflow:\s*auto/s);
  assert.doesNotMatch(practiceSource, /joke_mode|similar_voice|osaka_dialect|variation_mode/);
  assert.match(publicSessionSource, /\/api\/public-session/);
  assert.match(publicSessionSource, /\/auth\/google\/login/);
  assert.match(publicSessionSource, /session\.is_admin/);
  assert.match(publicSampleAudioSource, /\/api\/public-sample-audios/);
  assert.match(publicSampleAudioSource, /data-public-sample-feature/);
});

test("practice history admin uses separated practice history API", () => {
  assert.match(practiceAdminHtml, /SpeakLoop 管理/);
  assert.match(practiceAdminHtml, /Voice Lab/);
  assert.match(practiceAdminHtml, /data-public-access-settings/);
  assert.match(practiceAdminHtml, /data-public-access-features="speakloop"/);
  assert.match(practiceAdminHtml, /data-public-feature="speakloop"/);
  assert.match(practiceAdminHtml, /data-public-feature-setting="audio_max_bytes"/);
  assert.match(practiceAdminHtml, /data-public-setting="admin_google_emails"/);
  assert.doesNotMatch(practiceAdminHtml, /data-public-samples-admin/);
  assert.doesNotMatch(practiceAdminHtml, /data-public-sample-admin-feature="speakloop"/);
  assert.match(practiceAdminHtml, /id="practice-history-recordings"/);
  assert.match(practiceAdminHtml, /id="practice-history-outputs"/);
  assert.match(practiceAdminHtml, /data-practice-history-panel/);
  assert.match(practiceAdminHtml, /\/static\/app_public_access_settings\.js/);
  assert.doesNotMatch(practiceAdminHtml, /\/static\/app_public_sample_audio_admin\.js/);
  assert.match(practiceAdminHtml, /\/static\/app_practice_history\.js/);
  assert.match(practiceHistorySource, /fetch\("\/api\/practice-history"\)/);
  assert.match(practiceHistorySource, /payload\.settings\?\.enabled === false/);
  assert.match(practiceHistorySource, /panel\.hidden = true/);
  assert.match(practiceHistorySource, /settingsPanel\.open = true/);
  assert.match(practiceHistorySource, /ensureVoiceLabAudioControl/);
  assert.doesNotMatch(practiceHistorySource, /\/api\/audio-history/);
  assert.match(publicAccessSettingsSource, /\/api\/public-access-settings/);
  assert.match(publicAccessSettingsSource, /data-public-feature-setting/);
  assert.match(publicAccessSettingsSource, /保存済み/);
  assert.match(publicAccessSettingsSource, /管理画面を許可するGoogleメール/);
  assert.match(publicAccessSettingsSource, /setPublicAccessSaveButton/);
  assert.doesNotMatch(practiceAdminHtml, /public-samples-header-status/);
  assert.doesNotMatch(adminHtml, /id="user-settings-status"/);
  assert.doesNotMatch(adminHtml, /\/static\/app_admin_settings\.js/);
});

test("shared admin hides local-only history when the server disables it", () => {
  assert.match(adminHtml, /data-audio-history-panel/);
  assert.match(adminHistorySource, /settings\.enabled === false/);
  assert.match(adminHistorySource, /historyPanel\.hidden = true/);
  assert.doesNotMatch(adminHistorySource, /MO_AUDIO_HISTORY_ENABLED=1/);
});
