import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const source = await readFile(new URL("../src/mo_speech/web/app_user.js", import.meta.url), "utf8");
const userHtml = await readFile(new URL("../src/mo_speech/web/user.html", import.meta.url), "utf8");
const practiceHtml = await readFile(new URL("../src/mo_speech/web/practice.html", import.meta.url), "utf8");
const practiceSource = await readFile(new URL("../src/mo_speech/web/app_practice.js", import.meta.url), "utf8");
const practiceAdminHtml = await readFile(new URL("../src/mo_speech/web/practice_admin.html", import.meta.url), "utf8");
const practiceHistorySource = await readFile(new URL("../src/mo_speech/web/app_practice_history.js", import.meta.url), "utf8");
const vibevoiceHtml = await readFile(new URL("../src/mo_speech/web/vibevoice.html", import.meta.url), "utf8");
const vibevoiceSource = await readFile(new URL("../src/mo_speech/web/app_vibevoice.js", import.meta.url), "utf8");
const adminHtml = await readFile(new URL("../src/mo_speech/web/index.html", import.meta.url), "utf8");
const adminSource = await readFile(new URL("../src/mo_speech/web/app.js", import.meta.url), "utf8");
const styles = await readFile(new URL("../src/mo_speech/web/styles.css", import.meta.url), "utf8");

test("user page only shows warmup as a passive status dot", () => {
  assert.match(userHtml, /id="user-warmup-status"/);
  assert.doesNotMatch(userHtml, />じゅんび/);
  assert.match(source, /syncUserWarmupStatus\(seedVc\);/);
  assert.doesNotMatch(source, /maybeStartUserWarmup\(seedVc\)/);
  assert.doesNotMatch(source, /fetch\("\/api\/warmup"/);
  assert.match(source, /userWarmupStatus\.dataset\.state/);
  assert.doesNotMatch(source, /renderUserText\(userWarmupStatus/);
  assert.match(styles, /\.user-warmup-status\s*\{[^}]*left:\s*clamp/s);
  assert.match(styles, /\.user-warmup-status\[data-state="ready"\]::before/s);
  assert.match(styles, /\.user-warmup-status\[data-state="cold"\]\s*\{[^}]*background:\s*#ffffff/s);
  assert.match(styles, /\.user-warmup-status\[data-state="warming"\]\s*\{[^}]*animation:\s*warmup-dot-spin/s);
  assert.match(styles, /\.user-warmup-status\[data-state="unknown"\]\s*\{[^}]*border-style:\s*dotted/s);
});

test("admin page can start RunPod warmup manually", () => {
  assert.match(adminHtml, /id="runpod-warmup-button"/);
  assert.match(adminHtml, /id="runpod-warmup-status"/);
  assert.ok(adminHtml.indexOf("runpod-warmup-panel") < adminHtml.indexOf("operation_mode"));
  assert.match(adminSource, /runpodWarmupButton\.addEventListener\("click", startRunpodWarmup\)/);
  assert.match(adminSource, /fetch\("\/api\/warmup", \{ method: "POST" \}\)/);
  assert.match(adminSource, /fetch\(`\/api\/warmup\/\$\{encodeURIComponent\(jobId\)\}`\)/);
});

test("practice page keeps pronunciation training separate from conversion demo", () => {
  assert.match(practiceHtml, /発音練習/);
  assert.match(practiceHtml, /Pronunciation Practice/);
  assert.match(practiceHtml, /发音练习/);
  assert.match(practiceHtml, /言いたいことを話す/);
  assert.match(practiceHtml, /Say what you want/);
  assert.match(practiceHtml, /id="practice-target-language"/);
  assert.match(practiceHtml, /value="ja-JP"/);
  assert.match(practiceHtml, /value="zh-CN"/);
  assert.match(practiceHtml, /value="en-US"/);
  assert.match(practiceHtml, /id="practice-native-record-button"/);
  assert.match(practiceHtml, /id="practice-repeat-record-button"/);
  assert.match(practiceHtml, /id="practice-native-transcript"/);
  assert.match(practiceHtml, /id="practice-pinyin-toggle"/);
  assert.match(practiceHtml, /class="record-orb practice-record-orb"/);
  assert.match(practiceHtml, /class="record-level-meter"/);
  assert.match(practiceHtml, /id="practice-asr-model"/);
  assert.match(practiceHtml, /value="gpt-4o-transcribe"/);
  assert.match(practiceHtml, /value="gpt-4o-mini-transcribe"/);
  assert.match(practiceHtml, /value="whisper-1"/);
  assert.match(practiceHtml, /id="practice-speed-slider"/);
  assert.match(practiceHtml, /min="0\.25"/);
  assert.match(practiceHtml, /max="2"/);
  assert.match(practiceHtml, /step="0\.25"/);
  assert.equal((practiceHtml.match(/id="practice-result-panel"/g) || []).length, 1);
  assert.match(practiceHtml, /id="practice-segment-mode"/);
  assert.match(practiceHtml, /value="sentence"/);
  assert.match(practiceHtml, /value="punctuation"/);
  assert.doesNotMatch(practiceHtml, /id="practice-repeat-audio-button"/);
  assert.doesNotMatch(practiceHtml, /id="practice-compare-button"/);
  assert.doesNotMatch(practiceHtml, /id="practice-retry-button"/);
  assert.doesNotMatch(practiceHtml, /id="practice-next-button"/);
  assert.match(practiceHtml, /\/static\/app_practice\.js/);
  assert.match(practiceSource, /\/api\/practice\/prompts/);
  assert.match(practiceSource, /\/api\/practice\/attempts/);
  assert.match(practiceSource, /localStorage\.getItem/);
  assert.match(practiceSource, /localStorage\.setItem/);
  assert.match(practiceSource, /speed:/);
  assert.match(practiceSource, /Math\.round\(parsed \/ 0\.25\) \* 0\.25/);
  assert.match(practiceSource, /Math\.max\(0\.25/);
  assert.match(practiceSource, /segment_mode:/);
  assert.match(practiceSource, /asr_model:/);
  assert.match(practiceSource, /asr_timestamps/);
  assert.match(practiceSource, /include_pinyin/);
  assert.match(practiceSource, /currentTargetPinyinStatus/);
  assert.match(practiceSource, /renderTargetDisplay/);
  assert.match(practiceSource, /createPinyinRubyFragment/);
  assert.match(practiceSource, /document\.createElement\("ruby"\)/);
  assert.match(practiceSource, /document\.createElement\("rt"\)/);
  assert.match(practiceSource, /ピンインを生成できませんでした/);
  assert.match(practiceSource, /selectedTargetLanguage === "zh-CN" \? true : settings\.show_pinyin !== false/);
  assert.match(practiceSource, /pinyinToggle\.checked = true/);
  assert.match(practiceSource, /modelAudio\.playbackRate/);
  assert.match(practiceSource, /modelAudio\.defaultPlaybackRate/);
  assert.match(practiceSource, /loadedmetadata/);
  assert.match(practiceSource, /isComparisonPlaying/);
  assert.match(practiceSource, /stopComparisonPlayback/);
  assert.match(practiceSource, /比較再生/);
  assert.match(practiceSource, /renderRecognizedDiff/);
  assert.match(practiceSource, /renderMissingTargetDiff/);
  assert.match(practiceSource, /practice-diff-mismatch/);
  assert.match(practiceSource, /practice-diff-missing/);
  assert.match(practiceSource, /repeatAudio\.src/);
  assert.match(practiceSource, /splitPracticeSentences/);
  assert.match(practiceSource, /playAudioSegmentToEnd/);
  assert.match(styles, /\.practice-shell\s*\{[^}]*min-height:\s*100svh/s);
  assert.match(styles, /\.practice-language-grid\s*\{[^}]*grid-template-columns:\s*repeat\(3/s);
  assert.match(styles, /\.practice-recognized-text\s*\{[^}]*font-size:\s*clamp\(22px,\s*5\.8vw,\s*40px\)/s);
  assert.match(styles, /\.practice-target-text\.has-ruby/s);
  assert.match(styles, /\.practice-target-text rt/s);
  assert.match(styles, /\.practice-diff-mismatch/);
  assert.match(styles, /\.practice-diff-missing/);
  assert.match(styles, /\.practice-repeat-card\s*\{[^}]*order:\s*-1/s);
  assert.doesNotMatch(styles, /\.practice-actions/);
  assert.doesNotMatch(styles, /\.practice-target-text-box\s*\{[^}]*overflow:\s*auto/s);
  assert.doesNotMatch(practiceHtml, /joke_mode|similar_voice|osaka_dialect|variation_mode/);
});

test("practice history admin uses separated practice history API", () => {
  assert.match(practiceAdminHtml, /発音練習履歴/);
  assert.match(practiceAdminHtml, /id="practice-history-recordings"/);
  assert.match(practiceAdminHtml, /id="practice-history-outputs"/);
  assert.match(practiceAdminHtml, /\/static\/app_practice_history\.js/);
  assert.match(practiceHistorySource, /fetch\("\/api\/practice-history"\)/);
  assert.doesNotMatch(practiceHistorySource, /\/api\/audio-history/);
});

test("vibevoice page provides local skit generation controls", () => {
  assert.match(vibevoiceHtml, /VibeVoice/);
  assert.match(vibevoiceHtml, /id="vibevoice-script"/);
  assert.match(vibevoiceHtml, /name="script_file"/);
  assert.match(vibevoiceHtml, /id="vibevoice-script-file"/);
  assert.match(vibevoiceHtml, /name="voice_file_1"/);
  assert.match(vibevoiceHtml, /name="voice_file_4"/);
  assert.match(vibevoiceHtml, /name="cfg_scale"/);
  assert.match(vibevoiceHtml, /name="backend"/);
  assert.match(vibevoiceHtml, /value="runpod_serverless"/);
  assert.match(vibevoiceHtml, /name="model_id"/);
  assert.match(vibevoiceHtml, /value="vibevoice-1\.5b-pinned"/);
  assert.match(vibevoiceHtml, /value="vibevoice-realtime-0\.5b-latest"/);
  assert.match(vibevoiceHtml, /value="vibevoice-large-aoi-pinned"/);
  assert.match(vibevoiceHtml, /name="inference_steps"/);
  assert.match(vibevoiceHtml, /id="vibevoice-generate-button"/);
  assert.match(vibevoiceHtml, /id="vibevoice-audio"/);
  assert.match(vibevoiceHtml, /\/static\/app_vibevoice\.js/);
  assert.match(vibevoiceSource, /\/api\/vibevoice\/status/);
  assert.match(vibevoiceSource, /\/api\/vibevoice\/generate/);
  assert.match(vibevoiceSource, /runpod_serverless/);
  assert.match(vibevoiceSource, /audio_base64/);
  assert.match(vibevoiceSource, /handleScriptFileChange/);
  assert.match(vibevoiceSource, /file\.text\(\)/);
  assert.match(styles, /\.vibevoice-shell/);
});
