import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const source = await readFile(new URL("../src/mo_speech/web/app_user.js", import.meta.url), "utf8");
const userHtml = await readFile(new URL("../src/mo_speech/web/user.html", import.meta.url), "utf8");
const practiceSource = await readFile(new URL("../src/mo_speech/web/app_practice.js", import.meta.url), "utf8");
const practiceAdminHtml = await readFile(new URL("../src/mo_speech/web/practice_admin.html", import.meta.url), "utf8");
const practiceHistorySource = await readFile(new URL("../src/mo_speech/web/app_practice_history.js", import.meta.url), "utf8");
const vibevoiceHtml = await readFile(new URL("../src/mo_speech/web/vibevoice.html", import.meta.url), "utf8");
const vibevoiceSource = await readFile(new URL("../src/mo_speech/web/app_vibevoice.js", import.meta.url), "utf8");
const publicSessionSource = await readFile(new URL("../src/mo_speech/web/app_public_session.js", import.meta.url), "utf8");
const publicAccessSettingsSource = await readFile(new URL("../src/mo_speech/web/app_public_access_settings.js", import.meta.url), "utf8");
const publicSampleAudioSource = await readFile(new URL("../src/mo_speech/web/app_public_sample_audio.js", import.meta.url), "utf8");
const publicSampleAudioAdminSource = await readFile(new URL("../src/mo_speech/web/app_public_sample_audio_admin.js", import.meta.url), "utf8");
const sampleAudioControlsSource = await readFile(new URL("../src/mo_speech/web/app_sample_audio_controls.js", import.meta.url), "utf8");
const adminHtml = await readFile(new URL("../src/mo_speech/web/index.html", import.meta.url), "utf8");
const adminSource = await readFile(new URL("../src/mo_speech/web/app.js", import.meta.url), "utf8");
const adminHistorySource = await readFile(new URL("../src/mo_speech/web/app_history.js", import.meta.url), "utf8");
const adminSettingsSource = await readFile(new URL("../src/mo_speech/web/app_admin_settings.js", import.meta.url), "utf8");
const styles = await readFile(new URL("../src/mo_speech/web/styles.css", import.meta.url), "utf8");

test("user page only shows warmup as a passive status dot", () => {
  assert.match(userHtml, /id="user-warmup-status"/);
  assert.doesNotMatch(userHtml, />じゅんび/);
  assert.match(source, /syncUserWarmupStatus\(seedVc\);/);
  assert.doesNotMatch(source, /maybeStartUserWarmup\(seedVc\)/);
  assert.doesNotMatch(source, /fetch\("\/api\/warmup"/);
  assert.match(source, /userWarmupStatus\.dataset\.state/);
  assert.doesNotMatch(source, /renderUserText\(userWarmupStatus/);
  assert.match(styles, /\.user-warmup-status\s*\{[^}]*left:\s*clamp/s);
  assert.match(styles, /\.user-warmup-status\[data-state="ready"\]::before/s);
  assert.match(styles, /\.user-warmup-status\[data-state="cold"\]\s*\{[^}]*background:\s*#ffffff/s);
  assert.match(styles, /\.user-warmup-status\[data-state="warming"\]\s*\{[^}]*animation:\s*warmup-dot-spin/s);
  assert.match(styles, /\.user-warmup-status\[data-state="unknown"\]\s*\{[^}]*border-style:\s*dotted/s);
});

test("admin page can start RunPod warmup manually", () => {
  assert.match(adminHtml, /id="runpod-warmup-button"/);
  assert.match(adminHtml, /id="runpod-warmup-status"/);
  assert.match(adminHtml, /id="public-access-panel"/);
  assert.match(adminHtml, /data-public-access-features="fun,voice_conversion"/);
  assert.match(adminHtml, /data-public-feature="fun"/);
  assert.match(adminHtml, /data-public-feature="voice_conversion"/);
  assert.match(adminHtml, /data-public-feature-setting="audio_max_bytes"/);
  assert.match(adminHtml, /data-public-setting="google_login_required"/);
  assert.match(adminHtml, /data-public-samples-admin/);
  assert.match(adminHtml, /data-public-samples-features="fun,voice_conversion"/);
  assert.match(adminHtml, /data-public-sample-admin-feature="fun"/);
  assert.match(adminHtml, /data-public-sample-admin-feature="voice_conversion"/);
  assert.match(adminHtml, /\/static\/app_public_access_settings\.js/);
  assert.match(adminHtml, /\/static\/app_public_sample_audio_admin\.js/);
  assert.ok(adminHtml.indexOf("runpod-warmup-panel") < adminHtml.indexOf("operation_mode"));
  assert.match(adminSource, /runpodWarmupButton\.addEventListener\("click", startRunpodWarmup\)/);
  assert.match(adminSource, /fetch\("\/api\/warmup", \{ method: "POST" \}\)/);
  assert.match(adminSource, /fetch\(`\/api\/warmup\/\$\{encodeURIComponent\(jobId\)\}`\)/);
});

test("SpeakLoop controller keeps pronunciation training separate from conversion demo", () => {
  assert.match(practiceSource, /\/api\/practice\/recordings/);
  assert.match(practiceSource, /form\.append\("recording_intent", recordingIntent\)/);
  assert.match(practiceSource, /current_target_text/);
  assert.match(practiceSource, /localStorage\.getItem/);
  assert.match(practiceSource, /localStorage\.setItem/);
  assert.match(practiceSource, /speed:/);
  assert.doesNotMatch(practiceSource, /auto_play_comparison|autoPlayComparisonControl/);
  assert.match(practiceSource, /renderAttemptResult\(payload\);[\s\S]*setBusy\(false, ""\);[\s\S]*playComparisonAudios\(\)\.catch/);
  assert.doesNotMatch(practiceSource, /asr_model:/);
  assert.match(practiceSource, /Math\.round\(parsed \/ 0\.1\) \* 0\.1/);
  assert.match(practiceSource, /Math\.max\(0\.5/);
  assert.doesNotMatch(practiceSource, /openPracticeSettings/);
  assert.doesNotMatch(practiceSource, /closePracticeSettings/);
  assert.match(practiceSource, /syncCurrentLanguageLabel/);
  assert.match(practiceSource, /playAudioWithCurrentSpeed/);
  assert.doesNotMatch(practiceSource, /segment_mode:/);
  assert.doesNotMatch(practiceSource, /segmentModeSelect|nextPromptButton/);
  assert.match(practiceSource, /function practiceAsrModel\(\)\s*\{[^}]*return "whisper-1"/s);
  assert.match(practiceSource, /comparison_alignment/);
  assert.match(practiceSource, /include_pinyin/);
  assert.match(practiceSource, /currentTargetPinyinStatus/);
  assert.match(practiceSource, /renderTargetDisplay/);
  assert.match(practiceSource, /createPinyinRubyFragment/);
  assert.match(practiceSource, /document\.createElement\("ruby"\)/);
  assert.match(practiceSource, /document\.createElement\("rt"\)/);
  assert.match(practiceSource, /ピンインを生成できませんでした/);
  assert.match(practiceSource, /selectedTargetLanguage === "zh-CN" \? true : settings\.show_pinyin !== false/);
  assert.match(practiceSource, /pinyinToggle\.checked = true/);
  assert.match(practiceSource, /\[modelAudio, repeatAudio\]\.forEach/);
  assert.match(practiceSource, /audio\.playbackRate/);
  assert.match(practiceSource, /audio\.defaultPlaybackRate/);
  assert.match(practiceSource, /playing/);
  assert.match(practiceSource, /loadedmetadata/);
  assert.match(practiceSource, /isComparisonPlaying/);
  assert.match(practiceSource, /stopComparisonPlayback/);
  assert.match(practiceSource, /function cancelRecording/);
  assert.match(practiceSource, /recordingCancelled/);
  assert.match(practiceSource, /録音をキャンセルしました/);
  assert.match(practiceSource, /function pausePlaybackForRecording[\s\S]*modelAudio\.pause\(\)[\s\S]*repeatAudio\.pause\(\)/);
  assert.match(practiceSource, /比較再生/);
  assert.match(practiceSource, /setActiveRecordSlot/);
  assert.match(practiceSource, /repeatRecordButton/);
  assert.doesNotMatch(practiceSource, /const\s+\w+\s*=\s*currentTargetText\s*\?\s*"repeat"\s*:\s*"native"/);
  assert.match(practiceSource, /recognizedTextMatchesLearningLanguage/);
  assert.match(practiceSource, /hasCompleteComparisonAlignment/);
  assert.match(practiceSource, /renderRecognizedDiff/);
  assert.match(practiceSource, /renderMissingTargetDiff/);
  assert.match(practiceSource, /renderPracticeGrade/);
  assert.match(practiceSource, /practice-diff-correction/);
  assert.doesNotMatch(practiceSource, /抜け:/);
  assert.match(practiceSource, /practice-diff-mismatch/);
  assert.match(practiceSource, /practice-diff-missing/);
  assert.match(practiceSource, /repeatAudio\.src/);
  assert.match(practiceSource, /currentAttemptComparisonAlignment/);
  assert.match(practiceSource, /comparisonAlignmentPlaybackRanges/);
  assert.match(practiceSource, /全体比較再生/);
  assert.match(practiceSource, /フレーズごと比較再生/);
  assert.match(practiceSource, /canUsePhraseComparisonPlayback/);
  assert.match(practiceSource, /playAudioSegmentToEnd/);
  assert.match(styles, /\.practice-shell\s*\{[^}]*min-height:\s*100svh/s);
  assert.match(styles, /\.practice-shell\s*\{[^}]*align-content:\s*start/s);
  assert.match(styles, /\.practice-header h1\s*\{[^}]*font-size:\s*clamp\(26px/s);
  assert.match(styles, /\.practice-header-auth/);
  assert.match(styles, /\.public-status-bar/);
  assert.match(styles, /\.practice-flow\s*\{[^}]*grid-template-columns:\s*1fr/s);
  assert.match(styles, /\.practice-card-primary\s*\{[^}]*grid-template-columns:\s*auto minmax\(0,\s*1fr\)/s);
  assert.match(styles, /\.practice-repeat-record-button/);
  assert.match(styles, /\.practice-record-orb\.is-inactive/);
  assert.match(styles, /\.practice-record-orb\s*\{[^}]*width:\s*clamp\(64px,\s*8vw,\s*84px\)/s);
  assert.match(styles, /\.practice-quick-settings/);
  assert.match(styles, /\.practice-language-select/);
  assert.doesNotMatch(styles, /\.practice-auto-play-control/);
  assert.match(styles, /\.practice-grade-guide/);
  assert.doesNotMatch(styles, /\.practice-settings-overlay/);
  assert.doesNotMatch(styles, /\.practice-settings-dialog/);
  assert.match(styles, /\.public-auth-panel/);
  assert.match(styles, /\.public-access-admin/);
  assert.match(styles, /\.public-access-feature/);
  assert.doesNotMatch(styles, /\.practice-language-grid\s*\{[^}]*grid-template-columns:\s*repeat\(3/s);
  assert.doesNotMatch(styles, /\.practice-asr-row/);
  assert.doesNotMatch(styles, /\.practice-asr-help/);
  assert.match(styles, /\.practice-recognized-text\s*\{[^}]*font-size:\s*clamp\(19px,\s*3\.6vw,\s*32px\)/s);
  assert.match(styles, /\.practice-target-text\.has-ruby/s);
  assert.match(styles, /\.practice-target-text rt/s);
  assert.match(styles, /\.practice-diff-correction/);
  assert.match(styles, /\.practice-diff-mismatch/);
  assert.match(styles, /\.practice-diff-missing/);
  assert.doesNotMatch(styles, /\.practice-next-prompt-button/);
  assert.doesNotMatch(styles, /\.practice-repeat-card\s*\{[^}]*order:\s*-1/s);
  assert.doesNotMatch(styles, /\.practice-actions/);
  assert.doesNotMatch(styles, /\.practice-target-text-box\s*\{[^}]*overflow:\s*auto/s);
  assert.doesNotMatch(practiceSource, /joke_mode|similar_voice|osaka_dialect|variation_mode/);
  assert.match(publicSessionSource, /\/api\/public-session/);
  assert.match(publicSessionSource, /\/auth\/google\/login/);
  assert.match(publicSessionSource, /session\.is_admin/);
  assert.match(publicSampleAudioSource, /\/api\/public-sample-audios/);
  assert.match(publicSampleAudioSource, /data-public-sample-feature/);
});

test("practice history admin uses separated practice history API", () => {
  assert.match(practiceAdminHtml, /SpeakLoop 管理/);
  assert.match(practiceAdminHtml, /Voice Lab/);
  assert.match(practiceAdminHtml, /data-public-access-settings/);
  assert.match(practiceAdminHtml, /data-public-access-features="speakloop"/);
  assert.match(practiceAdminHtml, /data-public-feature="speakloop"/);
  assert.match(practiceAdminHtml, /data-public-feature-setting="audio_max_bytes"/);
  assert.match(practiceAdminHtml, /data-public-setting="admin_google_emails"/);
  assert.doesNotMatch(practiceAdminHtml, /data-public-samples-admin/);
  assert.doesNotMatch(practiceAdminHtml, /data-public-sample-admin-feature="speakloop"/);
  assert.match(practiceAdminHtml, /id="practice-history-recordings"/);
  assert.match(practiceAdminHtml, /id="practice-history-outputs"/);
  assert.match(practiceAdminHtml, /data-practice-history-panel/);
  assert.match(practiceAdminHtml, /\/static\/app_public_access_settings\.js/);
  assert.doesNotMatch(practiceAdminHtml, /\/static\/app_public_sample_audio_admin\.js/);
  assert.match(practiceAdminHtml, /\/static\/app_practice_history\.js/);
  assert.match(practiceHistorySource, /fetch\("\/api\/practice-history"\)/);
  assert.match(practiceHistorySource, /payload\.settings\?\.enabled === false/);
  assert.match(practiceHistorySource, /panel\.hidden = true/);
  assert.match(practiceHistorySource, /settingsPanel\.open = true/);
  assert.match(practiceHistorySource, /ensureVoiceLabAudioControl/);
  assert.doesNotMatch(practiceHistorySource, /\/api\/audio-history/);
  assert.match(publicAccessSettingsSource, /\/api\/public-access-settings/);
  assert.match(publicAccessSettingsSource, /data-public-feature-setting/);
  assert.match(publicAccessSettingsSource, /保存済み/);
  assert.match(publicAccessSettingsSource, /管理画面を許可するGoogleメール/);
  assert.match(publicAccessSettingsSource, /setPublicAccessSaveButton/);
  assert.match(publicSampleAudioAdminSource, /\/api\/public-sample-audios/);
  assert.match(publicSampleAudioAdminSource, /method:\s*"DELETE"/);
  assert.match(publicSampleAudioAdminSource, /data-public-sample-admin-feature/);
  assert.match(publicSampleAudioAdminSource, /data-public-sample-delete/);
  assert.match(publicSampleAudioAdminSource, /setPublicSampleActionButton/);
  assert.match(publicSampleAudioAdminSource, /保存中…/);
  assert.match(publicSampleAudioAdminSource, /保存済み/);
  assert.match(publicSampleAudioAdminSource, /削除中…/);
  assert.match(publicSampleAudioAdminSource, /dataset\.state.*success/s);
  assert.doesNotMatch(practiceAdminHtml, /public-samples-header-status/);
  assert.match(adminHtml, /id="user-settings-status"[^>]*role="status"/);
  assert.match(adminSettingsSource, /保存中…/);
  assert.match(adminSettingsSource, /保存済み/);
});

test("shared admin hides local-only history when the server disables it", () => {
  assert.match(adminHtml, /data-audio-history-panel/);
  assert.match(adminHistorySource, /settings\.enabled === false/);
  assert.match(adminHistorySource, /historyPanel\.hidden = true/);
  assert.doesNotMatch(adminHistorySource, /MO_AUDIO_HISTORY_ENABLED=1/);
});

test("vibevoice page provides local skit generation controls", () => {
  assert.match(vibevoiceHtml, /VibeVoice/);
  assert.match(vibevoiceHtml, /href="\/skitvoice"/);
  assert.match(vibevoiceHtml, /data-public-access-settings/);
  assert.match(vibevoiceHtml, /data-public-access-features="skitvoice"/);
  assert.match(vibevoiceHtml, /data-public-feature="skitvoice"/);
  assert.match(vibevoiceHtml, /data-public-feature-setting="script_max_chars"/);
  assert.doesNotMatch(vibevoiceHtml, /data-public-feature-setting="reference_url_duration_max_seconds"/);
  assert.match(vibevoiceHtml, /\/static\/app_public_access_settings\.js/);
  assert.match(vibevoiceHtml, /data-public-samples-admin/);
  assert.match(vibevoiceHtml, /data-public-samples-features="skitvoice"/);
  assert.match(vibevoiceHtml, /data-public-sample-admin-feature="skitvoice"/);
  assert.equal((vibevoiceHtml.match(/data-public-sample-language="(?:ja-JP|zh-CN|en-US)"/g) || []).length, 3);
  assert.ok(vibevoiceHtml.indexOf('data-public-sample-language="en-US"') < vibevoiceHtml.indexOf('data-public-sample-language="zh-CN"'));
  assert.ok(vibevoiceHtml.indexOf('data-public-sample-language="zh-CN"') < vibevoiceHtml.indexOf('data-public-sample-language="ja-JP"'));
  assert.match(vibevoiceHtml, /<h2>出力音声サンプル<\/h2>/);
  assert.match(vibevoiceHtml, /skitvoice-samples-admin/);
  assert.doesNotMatch(vibevoiceHtml, /<label>タイトル/);
  assert.doesNotMatch(vibevoiceHtml, /data-public-sample-details/);
  assert.match(vibevoiceHtml, /public-sample-file-button/);
  assert.equal((vibevoiceHtml.match(/data-sample-audio-custom/g) || []).length, 3);
  assert.match(vibevoiceHtml, /\/static\/app_sample_audio_controls\.js/);
  assert.match(sampleAudioControlsSource, /sample-audio-play-button/);
  assert.match(sampleAudioControlsSource, /sample-audio-seek/);
  assert.match(sampleAudioControlsSource, /timeupdate/);
  assert.match(sampleAudioControlsSource, /loadedmetadata/);
  assert.match(sampleAudioControlsSource, /aria-label/);
  assert.match(vibevoiceHtml, /\/static\/app_public_sample_audio_admin\.js/);
  assert.match(vibevoiceHtml, /public-samples-header-status/);
  assert.match(vibevoiceHtml, /id="vibevoice-script"/);
  assert.match(vibevoiceHtml, /name="script_file"/);
  assert.match(vibevoiceHtml, /id="vibevoice-script-file"/);
  assert.match(vibevoiceHtml, /name="voice_file_1"/);
  assert.match(vibevoiceHtml, /name="voice_file_4"/);
  assert.match(vibevoiceHtml, /data-saved-voice-slot="1"/);
  assert.match(vibevoiceHtml, /data-saved-voice-slot="4"/);
  assert.match(vibevoiceHtml, /data-saved-voice-preview-slot="1"/);
  assert.match(vibevoiceHtml, /data-saved-voice-preview-slot="4"/);
  assert.match(vibevoiceHtml, /data-record-voice-slot="1"/);
  assert.match(vibevoiceHtml, /data-record-voice-slot="4"/);
  assert.equal((vibevoiceHtml.match(/data-tab-audio-slot=/g) || []).length, 4);
  assert.doesNotMatch(vibevoiceHtml, /data-tab-audio-slot="1"[^>]*data-local-reference-url/);
  assert.match(vibevoiceHtml, /id="vibevoice-reference-url"/);
  assert.match(vibevoiceHtml, /id="vibevoice-reference-url-start"/);
  assert.match(vibevoiceHtml, /id="vibevoice-reference-url-duration"/);
  assert.match(vibevoiceHtml, /id="vibevoice-reference-url-button"/);
  assert.match(vibevoiceHtml, /id="vibevoice-reference-url-dialog"/);
  assert.match(vibevoiceHtml, /data-reference-url-open-slot="1" data-local-reference-url hidden/);
  assert.match(vibevoiceHtml, /data-reference-url-open-slot="4" data-local-reference-url hidden/);
  assert.match(vibevoiceHtml, /data-reference-url-display-slot="1" data-local-reference-url hidden/);
  assert.match(vibevoiceHtml, />URL<\/button>/);
  assert.match(vibevoiceHtml, /id="vibevoice-reference-url-button"[^>]*>設定<\/button>/);
  assert.doesNotMatch(vibevoiceHtml, /class="vibevoice-reference-url-panel"/);
  assert.match(styles, /\.vibevoice-upload-slot\s*\{[^}]*grid-template-columns:\s*auto minmax\(0,\s*1fr\)/s);
  assert.match(styles, /\.vibevoice-upload-actions\s*\{[^}]*flex-wrap:\s*wrap/s);
  assert.match(styles, /\.vibevoice-upload-actions\s*\{[^}]*grid-column:\s*2/s);
  assert.match(styles, /\.vibevoice-upload-action,\s*\.vibevoice-url-slot-button,\s*\.vibevoice-record-slot-button,\s*\.vibevoice-tab-audio-slot-button\s*\{[^}]*min-width:\s*52px/s);
  assert.match(vibevoiceHtml, /name="cfg_scale"/);
  assert.match(vibevoiceHtml, /class="vibevoice-workspace"/);
  assert.match(vibevoiceHtml, /class="vibevoice-control-stack"/);
  assert.match(vibevoiceHtml, /class="vibevoice-debug-runtime"/);
  assert.doesNotMatch(vibevoiceHtml, /class="vibevoice-status-card"/);
  assert.match(vibevoiceHtml, /id="vibevoice-cfg-scale"[^>]*name="cfg_scale"[^>]*type="range"/s);
  assert.match(vibevoiceHtml, /id="vibevoice-inference-steps"[^>]*name="inference_steps"[^>]*type="range"/s);
  assert.match(vibevoiceHtml, /data-vibevoice-range-output="cfg_scale"/);
  assert.match(vibevoiceHtml, /data-vibevoice-range-output="line_gap"/);
  assert.match(vibevoiceHtml, /name="backend"/);
  assert.match(vibevoiceHtml, /value="runpod_serverless"/);
  assert.match(vibevoiceHtml, /name="model_id"/);
  assert.match(vibevoiceHtml, /value="vibevoice-1\.5b-pinned"/);
  assert.doesNotMatch(vibevoiceHtml, /value="vibevoice-realtime-0\.5b-latest"/);
  assert.match(vibevoiceHtml, /value="vibevoice-large-aoi-pinned"[^>]*data-vibevoice-backends="runpod_serverless"/);
  assert.match(vibevoiceHtml, /name="output_language"/);
  assert.match(vibevoiceHtml, /value="en-US"[^>]*selected[^>]*>🇺🇸 English/);
  assert.match(vibevoiceHtml, /value="zh-CN"[^>]*>🇨🇳 中文/);
  assert.match(vibevoiceHtml, /value="ja-JP"[^>]*>🇯🇵 日本語（低品質）/);
  assert.match(vibevoiceHtml, /name="translate_script"/);
  assert.match(vibevoiceHtml, /日本語台本を出力言語へ翻訳/);
  assert.match(vibevoiceHtml, /name="inference_steps"/);
  assert.match(vibevoiceHtml, /id="vibevoice-reset-settings-button"/);
  assert.match(vibevoiceHtml, /class="vibevoice-parameter-guide"/);
  assert.match(vibevoiceHtml, /name="directed_line_mode"/);
  assert.match(vibevoiceHtml, /name="directed_retry_low_score"/);
  assert.match(vibevoiceHtml, /name="directed_retry_score_threshold"/);
  assert.match(vibevoiceHtml, /name="directed_retry_max_multiplier"/);
  assert.match(vibevoiceHtml, /id="vibevoice-directed-line-mode"[^>]*checked/s);
  assert.match(vibevoiceHtml, /id="vibevoice-directed-retry-low-score"[^>]*checked/s);
  assert.match(vibevoiceHtml, /id="vibevoice-directed-retry-max-multiplier"[^>]*value="1"/s);
  assert.match(vibevoiceHtml, /指定台詞を1行生成してASR再配置/);
  assert.match(vibevoiceHtml, /低スコア行だけ再生成/);
  assert.match(vibevoiceHtml, /パラメータ目安/);
  assert.match(vibevoiceHtml, /まず 1\.1-1\.5/);
  assert.match(vibevoiceHtml, /試作は 10-15/);
  assert.match(vibevoiceHtml, /まず 0\.75-0\.95/);
  assert.match(vibevoiceHtml, /基本 0、不安定なら 30-50/);
  assert.match(vibevoiceHtml, /自然会話は 0\.4-0\.7秒/);
  assert.match(vibevoiceHtml, /再生成スコア閾値/);
  assert.match(vibevoiceHtml, /品質優先なら 0\.70-0\.75/);
  assert.match(vibevoiceHtml, /再生成強度/);
  assert.match(vibevoiceHtml, /11行台本なら1\.0で6行、2\.0で12行/);
  assert.match(vibevoiceHtml, /id="vibevoice-generate-button"/);
  assert.match(vibevoiceHtml, /id="vibevoice-cancel-button"/);
  assert.match(vibevoiceHtml, /id="vibevoice-job-progress"/);
  assert.match(vibevoiceHtml, /id="vibevoice-timing"/);
  assert.match(vibevoiceHtml, /id="vibevoice-progress-log"/);
  assert.match(vibevoiceHtml, /id="vibevoice-audio"/);
  assert.match(vibevoiceHtml, /id="vibevoice-download"[^>]*download="vibevoice-output\.wav"/);
  assert.match(vibevoiceHtml, /id="vibevoice-copy-diagnostics"/);
  assert.match(vibevoiceHtml, /id="vibevoice-speaker-scripts"/);
  assert.match(vibevoiceHtml, /id="vibevoice-artifacts"/);
  assert.match(vibevoiceHtml, /\/static\/app_vibevoice\.js/);
  assert.match(vibevoiceSource, /\/api\/vibevoice\/status/);
  assert.match(vibevoiceSource, /\/api\/vibevoice\/jobs/);
  assert.match(vibevoiceSource, /cancelVibeVoiceJob/);
  assert.match(vibevoiceSource, /requiredVoiceSlotsFromScript/);
  assert.match(vibevoiceSource, /runpod_serverless/);
  assert.match(vibevoiceSource, /Sync Timeout/);
  assert.match(vibevoiceSource, /audio_base64/);
  assert.match(vibevoiceSource, /renderSpeakerScripts/);
  assert.match(vibevoiceSource, /renderArtifacts/);
  assert.match(vibevoiceSource, /function extensionForMimeType/);
  assert.match(vibevoiceSource, /downloadLink\.download = `vibevoice-output\.\$\{extensionForMimeType\(audioMimeType\)\}`/);
  assert.match(vibevoiceSource, /audio\/mpeg/);
  assert.match(vibevoiceSource, /copyDiagnosticsButton\?\.addEventListener\("click", copyDiagnosticsToClipboard\)/);
  assert.match(vibevoiceSource, /navigator\.clipboard\.writeText/);
  assert.match(vibevoiceSource, /copyTextWithFallback/);
  assert.match(vibevoiceSource, /runpod_artifacts/);
  assert.match(vibevoiceSource, /返却サイズを抑えるため/);
  assert.match(vibevoiceSource, /handleScriptFileChange/);
  assert.match(vibevoiceSource, /file\.text\(\)/);
  assert.match(vibevoiceSource, /indexedDB\.open/);
  assert.match(vibevoiceSource, /savedVoiceFilesBySlot/);
  assert.match(vibevoiceSource, /savedVoicePreviews/);
  assert.match(vibevoiceSource, /renderSavedVoicePreview/);
  assert.match(vibevoiceSource, /URL\.createObjectURL\(record\.blob\)/);
  assert.match(vibevoiceSource, /navigator\.mediaDevices\.getUserMedia/);
  assert.match(vibevoiceSource, /navigator\.mediaDevices\.getDisplayMedia/);
  assert.doesNotMatch(vibevoiceSource, /function confirmTabAudioRights\(\)/);
  assert.match(vibevoiceSource, /getAudioTracks\(\)/);
  assert.match(vibevoiceSource, /YouTube JS Runtime/);
  assert.match(vibevoiceSource, /タブの音声を共有/);
  assert.match(vibevoiceSource, /recordingType:\s*"tab"/);
  assert.match(vibevoiceSource, /speaker-\$\{slot\}-tab-reference/);
  assert.match(vibevoiceSource, /new MediaRecorder/);
  assert.match(vibevoiceSource, /recorded-reference/);
  assert.match(vibevoiceSource, /録音を停止してから生成してください/);
  assert.match(vibevoiceSource, /appendVoiceFiles/);
  assert.match(vibevoiceSource, /body\.set\(input\.name,\s*saved\.blob/s);
  assert.match(vibevoiceSource, /function appendVoiceUrlReference/);
  assert.match(vibevoiceSource, /body\.set\(`voice_url_\$\{slot\}`/);
  assert.match(vibevoiceSource, /handleReferenceUrlUse/);
  assert.match(vibevoiceSource, /handleReferenceUrlClear/);
  assert.match(vibevoiceSource, /referenceUrlRecordsBySlot\.delete\(slot\)/);
  assert.match(vibevoiceSource, /openReferenceUrlDialog/);
  assert.match(vibevoiceSource, /closeReferenceUrlDialog/);
  assert.match(vibevoiceSource, /renderReferenceUrlRecord/);
  assert.match(vibevoiceSource, /referenceUrlDialog\.showModal\(\)/);
  assert.match(vibevoiceSource, /referenceUrlButton\.textContent = "設定"/);
  assert.match(vibevoiceSource, /生成ボタンで送信します/);
  assert.doesNotMatch(vibevoiceSource, /\/api\/vibevoice\/reference-audio-from-url/);
  assert.doesNotMatch(vibevoiceSource, /取得中\.\.\./);
  assert.match(vibevoiceSource, /data-vibevoice-range/);
  assert.match(vibevoiceSource, /renderRangeValue/);
  assert.match(vibevoiceSource, /vibevoiceSettingsStorageKey/);
  assert.match(vibevoiceSource, /dataset\.vibevoiceMode/);
  assert.match(vibevoiceSource, /mo-speech-vibevoice-simple-draft/);
  assert.match(vibevoiceSource, /1 あっ、こんにちは〜\\n2 こんにちは。ご無沙汰してます。\\n1 元気ですか？最近、どうしてます？/);
  assert.match(vibevoiceSource, /loadVibeVoiceDraft/);
  assert.match(vibevoiceSource, /saveVibeVoiceDraft/);
  assert.match(vibevoiceSource, /reference_urls: serializeReferenceUrlRecords\(\)/);
  assert.match(vibevoiceSource, /restoreReferenceUrlRecords\(draft\.reference_urls\)/);
  assert.match(vibevoiceSource, /function serializeReferenceUrlRecords\(\)/);
  assert.match(vibevoiceSource, /function restoreReferenceUrlRecords\(value\)/);
  assert.match(vibevoiceSource, /function normalizeReferenceUrlRecord\(record\)/);
  assert.match(vibevoiceSource, /saveVibeVoiceDraft\(\);\s*setReferenceUrlStatus\(referenceUrlUseMessage/s);
  assert.match(vibevoiceSource, /progress_log/);
  assert.match(vibevoiceSource, /localStorage\.getItem/);
  assert.match(vibevoiceSource, /localStorage\.setItem/);
  assert.match(vibevoiceSource, /resetVibeVoiceGenerationSettings/);
  assert.match(vibevoiceSource, /defaultGenerationSettings/);
  assert.match(vibevoiceSource, /directedTargetMaxChars\s*=\s*120/);
  assert.match(vibevoiceSource, /directedLineMaxChars\s*=\s*180/);
  assert.match(vibevoiceSource, /validateDirectedLineModeScript/);
  assert.match(vibevoiceSource, /1行だけで/);
  assert.match(vibevoiceSource, /分割して生成します/);
  assert.match(vibevoiceSource, /scriptInput\.addEventListener\("input"[\s\S]*updateLineByLineAutoState\(\)[\s\S]*saveVibeVoiceDraft\(\)/);
  assert.match(vibevoiceSource, /handleScriptFileChange[\s\S]*saveVibeVoiceDraft\(\)/);
  assert.match(vibevoiceSource, /"backend"/);
  assert.match(vibevoiceSource, /"model_id"/);
  assert.match(vibevoiceSource, /function updateModelAvailability\(\)/);
  assert.match(vibevoiceSource, /dataset\.vibevoiceBackends/);
  assert.match(vibevoiceSource, /option\.disabled = !allowedBackends\.includes\(backend\)/);
  assert.match(vibevoiceSource, /"cfg_scale"/);
  assert.match(vibevoiceSource, /"line_by_line"/);
  assert.match(vibevoiceSource, /"directed_line_mode"/);
  assert.match(vibevoiceSource, /"directed_retry_low_score"/);
  assert.match(vibevoiceSource, /"directed_retry_score_threshold"/);
  assert.match(vibevoiceSource, /"directed_retry_max_multiplier"/);
  assert.match(vibevoiceSource, /body\.set\("directed_line_mode",\s*directedLineModeControl\.checked \? "true" : "false"\)/);
  assert.match(vibevoiceSource, /body\.set\("directed_retry_low_score",\s*effectiveDirectedRetryLowScoreEnabled\(\) \? "true" : "false"\)/);
  assert.match(styles, /\.vibevoice-shell/);
  assert.match(styles, /\.vibevoice-workspace/);
  assert.match(styles, /\.vibevoice-range-control/);
  assert.match(styles, /\.vibevoice-url-slot-button/);
  assert.match(styles, /\.vibevoice-record-slot-button/);
  assert.match(styles, /\.vibevoice-tab-audio-slot-button/);
  assert.match(styles, /\.vibevoice-record-slot-button\[data-recording="true"\]/);
  assert.match(styles, /\.vibevoice-reference-url-dialog/);
  assert.match(styles, /\.vibevoice-url-voice/);
  assert.match(styles, /\.vibevoice-parameter-guide/);
  assert.match(styles, /\.vibevoice-debug-runtime/);
  assert.match(styles, /\.vibevoice-progress-bar/);
  assert.match(styles, /\.vibevoice-progress-log/);
  assert.match(styles, /\.vibevoice-saved-voice/);
});

test("vibevoice auto line-by-line state is reflected in the UI without overwriting the saved preference", () => {
  assert.match(vibevoiceSource, /const autoLineByLineMinLines = 4/);
  assert.match(vibevoiceSource, /const autoLineByLineMinChars = 180/);
  assert.match(vibevoiceSource, /let lineByLineUserPreference/);
  assert.match(vibevoiceSource, /function selectedModelAllowsAutoLineByLine\(\)/);
  assert.match(vibevoiceSource, /dataset\.vibevoiceAutoLineByLine !== "false"/);
  assert.match(vibevoiceSource, /function updateLineByLineAutoState\(\)/);
  assert.match(vibevoiceSource, /lineByLineControl\.disabled = autoLineByLine \|\| directedLineModeEnabled/);
  assert.match(vibevoiceSource, /lineByLineControl\.checked = directedLineModeEnabled \? false : autoLineByLine \|\| lineByLineUserPreference/);
  assert.match(vibevoiceSource, /settings\[control\.name\] = lineByLineUserPreference/);
  assert.match(vibevoiceSource, /"output_language"/);
  assert.match(vibevoiceSource, /ensureVoiceLabAudioControl/);
  assert.match(vibevoiceSource, /hideVoiceLabAudioControl/);
  assert.match(vibevoiceSource, /body\.set\("translate_script", "auto"\)/);
  assert.match(vibevoiceSource, /JSON\.stringify\(\{ seed_script: scriptInput\.value \}\)/);
  assert.match(vibevoiceSource, /body\.set\("line_by_line",\s*effectiveLineByLineEnabled\(\) \? "true" : "false"\)/);
  assert.match(vibevoiceSource, /function updateDirectedLineModeState\(\)/);
  assert.match(vibevoiceHtml, /data-auto-line-by-line/);
  assert.match(vibevoiceHtml, /value="vibevoice-large-aoi-pinned"[^>]*data-vibevoice-auto-line-by-line="false"/);
  assert.match(styles, /\.vibevoice-switch\[data-auto-line-by-line="true"\]/);
});

test("vibevoice progress animation only runs while a job is active", () => {
  const baseProgressSpanRule = styles.match(/\.vibevoice-progress-bar span\s*\{(?<body>[^}]*)\}/)?.groups?.body || "";
  assert.match(vibevoiceSource, /jobProgress\.dataset\.state = "running"/);
  assert.match(vibevoiceSource, /jobProgress\.dataset\.state = "complete"/);
  assert.match(vibevoiceSource, /renderProgressPercent/);
  assert.match(vibevoiceSource, /renderProgressPercent\(null,\s*"idle"\)/);
  assert.match(vibevoiceSource, /progressPercentFromLabel/);
  assert.match(vibevoiceSource, /行単位生成\\s\+\\d\+\\\/\\d\+/);
  assert.match(vibevoiceSource, /aria-valuenow/);
  assert.match(styles, /\.vibevoice-job-progress\[data-state="complete"\]\s+\.vibevoice-progress-bar\s*\{[^}]*display:\s*none/s);
  assert.match(
    styles,
    /\.vibevoice-job-progress\[data-state="running"\]\[data-progress="indeterminate"\]\s+\.vibevoice-progress-bar span\s*\{[^}]*animation:\s*vibevoice-progress-slide/s,
  );
  assert.match(styles, /\.vibevoice-job-progress\[data-progress="determinate"\]\s+\.vibevoice-progress-bar span/s);
  assert.doesNotMatch(baseProgressSpanRule, /animation:/);
});
