const languageLabels = {
  auto: "自動判定",
  af: "アフリカーンス語",
  ar: "アラビア語",
  hy: "アルメニア語",
  az: "アゼルバイジャン語",
  be: "ベラルーシ語",
  bs: "ボスニア語",
  bg: "ブルガリア語",
  ca: "カタルーニャ語",
  cs: "チェコ語",
  da: "デンマーク語",
  de: "ドイツ語",
  el: "ギリシャ語",
  es: "スペイン語",
  et: "エストニア語",
  fa: "ペルシア語",
  fi: "フィンランド語",
  fr: "フランス語",
  gl: "ガリシア語",
  he: "ヘブライ語",
  hi: "ヒンディー語",
  hr: "クロアチア語",
  hu: "ハンガリー語",
  is: "アイスランド語",
  "id-ID": "インドネシア語",
  it: "イタリア語",
  "ja-JP": "日本語",
  kk: "カザフ語",
  kn: "カンナダ語",
  ko: "韓国語",
  lt: "リトアニア語",
  lv: "ラトビア語",
  mi: "マオリ語",
  mk: "マケドニア語",
  mr: "マラーティー語",
  ms: "マレー語",
  ne: "ネパール語",
  nl: "オランダ語",
  no: "ノルウェー語",
  pl: "ポーランド語",
  pt: "ポルトガル語",
  ro: "ルーマニア語",
  ru: "ロシア語",
  sk: "スロバキア語",
  sl: "スロベニア語",
  sr: "セルビア語",
  sv: "スウェーデン語",
  sw: "スワヒリ語",
  ta: "タミル語",
  th: "タイ語",
  tl: "タガログ語",
  tr: "トルコ語",
  uk: "ウクライナ語",
  ur: "ウルドゥー語",
  vi: "ベトナム語",
  cy: "ウェールズ語",
  "zh-CN": "中国語（普通話）",
  "en-US": "英語",
};

const openAiTargetLanguages = [
  "id-ID",
  "ja-JP",
  "zh-CN",
  "en-US",
  ...Object.keys(languageLabels).filter((language) => !["auto", "id-ID", "ja-JP", "zh-CN", "en-US"].includes(language)),
];

const seedVcPresets = {
  fast: {
    diffusion_steps: 10,
    reference_max_seconds: 5,
    length_adjust: 1.0,
    inference_cfg_rate: 0.7,
  },
  reasonable: {
    diffusion_steps: 25,
    reference_max_seconds: 8,
    length_adjust: 1.0,
    inference_cfg_rate: 0.7,
  },
  quality: {
    diffusion_steps: 30,
    reference_max_seconds: 10,
    length_adjust: 1.0,
    inference_cfg_rate: 0.7,
  },
  best: {
    diffusion_steps: 50,
    reference_max_seconds: 15,
    length_adjust: 1.0,
    inference_cfg_rate: 0.7,
  },
};
